name: publish
description: Steps that run after a successful release
inputs:
  token:
    description: "GitHub token for creating and grooming release PRs, defaults to using secrets.GITHUB_TOKEN"
    required: false
    default: ${{ github.token }}
  upload_url:
    description: todo
    required: true
  html_url:
    description: todo
    required: true
  tag_name:
    description: todo
    required: true
  major:
    description: todo
    required: true
  minor:
    description: todo
    required: true
  patch:
    description: todo
    required: true
  sha:
    description: todo
    required: true
  pr:
    description: todo
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2.4.0

    - uses: actions/cache@v2.1.7
      with:
        key: ${{ runner.os }}-asdf2-${{ hashFiles('task', '.tool-versions', '.tool-versions.lock', '.asdf/.plugin-versions') }}
        restore-keys: ${{ runner.os }}-asdf2-
        path: |
          ./.asdf/bin/**/*
          ./.asdf/v0.9.0/**/*

    - run: ./task build VERSION=${{ inputs.major }}.${{ inputs.minor }}.${{ inputs.patch }}
      shell: bash

    - uses: shogo82148/actions-upload-release-asset@v1.5.0
      with:
        github_token: ${{ inputs.token }}
        upload_url: ${{ inputs.upload_url }}
        asset_path: ./assets/*
