on: { workflow_call: {} }

env:
  CI: true
  GITHUB_CONTEXT: ${{ toJson(github) }}
  GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0
      - name: Cache ASDF Tools
        uses: actions/cache@v2.1.7
        with:
          key: ${{ runner.os }}-asdf2-${{ hashFiles('task', '.tool-versions', '.tool-versions.lock', '.asdf/.plugin-versions') }}
          restore-keys: ${{ runner.os }}-asdf2-
          path: |
            ./.asdf/bin/**/*
            ./.asdf/v0.9.0/**/*
      - name: Cache Node Modules
        uses: actions/cache@v2.1.7
        with:
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-
          path: |
            ~/.npm
            ./node_modules
      - run: ./task lint

  test:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2.4.0
      - name: Cache ASDF Tools
        uses: actions/cache@v2.1.7
        with:
          key: ${{ runner.os }}-asdf2-${{ hashFiles('task', '.tool-versions', '.tool-versions.lock', '.asdf/.plugin-versions') }}
          restore-keys: ${{ runner.os }}-asdf2-
          path: |
            ./.asdf/bin/**/*
            ./.asdf/v0.9.0/**/*
      - run: ./task test
