on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - edited

env:
  CI: true
  GITHUB_CONTEXT: ${{ toJson(github) }}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - name: Cache ASDF Tools
        uses: actions/cache@v2.1.6
        with:
          key: ${{ runner.os }}-asdf-${{ hashFiles('task', '.tool-versions.lock', '.asdf/.plugin-versions') }}
          restore-keys: ${{ runner.os }}-asdf-
          path: |
            ./.asdf/**/*
      - name: Cache Node Modules
        uses: actions/cache@v2.1.6
        with:
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-
          path: |
            ~/.npm
            ./node_modules
      - run: ./task lint

  test:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Cache ASDF Tools
        uses: actions/cache@v2.1.6
        with:
          key: ${{ runner.os }}-asdf-${{ hashFiles('task', '.tool-versions.lock', '.asdf/.plugin-versions') }}
          restore-keys: ${{ runner.os }}-asdf-
          path: |
            ./.asdf/**/*
      - run: ./task test
