on:
  workflow_call:
    inputs:
      token: { type: string, required: true }
      upload_url: { type: string, required: true }
      html_url: { type: string, required: true }
      tag_name: { type: string, required: true }
      major: { type: string, required: true }
      minor: { type: string, required: true }
      patch: { type: string, required: true }
      sha: { type: string, required: true }
      pr: { type: string, required: true }

env:
  CI: true
  GITHUB_CONTEXT: ${{ toJson(github) }}
  GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0

      - uses: actions/cache@v2.1.7
        with:
          key: ${{ runner.os }}-asdf2-${{ hashFiles('task', '.tool-versions', '.tool-versions.lock', '.asdf/.plugin-versions') }}
          restore-keys: ${{ runner.os }}-asdf2-
          path: |
            ./.asdf/bin/**/*
            ./.asdf/v0.9.0/**/*

      - run: ./task build VERSION=${{ inputs.major }}.${{ inputs.minor }}.${{ inputs.patch }}

      - uses: shogo82148/actions-upload-release-asset@v1.5.0
        with:
          github_token: ${{ inputs.token }}
          upload_url: ${{ inputs.upload_url }}
          asset_path: ./assets/*
