on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - edited

env:
  CI: true
  GITHUB_CONTEXT: ${{ toJson(github) }}
  GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  checks:
    # see: https://github.com/github/feedback/discussions/10679
    uses: brad-jones/asdf-bootstrap/.github/workflows/checks.yml@master
