on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - edited

env:
  CI: true
  GITHUB_CONTEXT: ${{ toJson(github) }}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Foo Bar"
