on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - edited

env:
  CI: true
  GITHUB_CONTEXT: ${{ toJson(github) }}

jobs:
  checks:
    uses: ./.github/workflows/checks.yml
