on: { push: { branches: [master] } }

env:
  CI: true
  GITHUB_CONTEXT: ${{ toJson(github) }}

jobs:
  checks:
    if: github.event.head_commit.committer.username != 'web-flow'
    uses: ./.github/workflows/checks.yml

  release:
    needs: [checks]
    # see: https://github.com/actions/runner/issues/491
    if: always() && (needs.checks.result == 'success' || needs.checks.result == 'skipped')
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: false
    runs-on: ubuntu-latest
    steps:
      - id: generate_token
        uses: tibdex/github-app-token@v1.5.1
        with:
          app_id: ${{ secrets.BOT_ID }}
          private_key: ${{ secrets.BOT_KEY }}

      - id: release_please
        uses: GoogleCloudPlatform/release-please-action@v3.1
        with:
          token: ${{ steps.generate_token.outputs.token }}
          release-type: simple
          changelog-types: |
            [
              {"type":"feat","section":"Features","hidden":false},
              {"type":"fix","section":"Bug Fixes","hidden":false},
              {"type":"build","section":"Automation","hidden":false},
              {"type":"ci","section":"Automation","hidden":false},
              {"type":"docs","section":"Miscellaneous","hidden":false},
              {"type":"perf","section":"Miscellaneous","hidden":false},
              {"type":"refactor","section":"Miscellaneous","hidden":false},
              {"type":"style","section":"Miscellaneous","hidden":false},
              {"type":"test","section":"Miscellaneous","hidden":false},
              {"type":"chore","section":"Miscellaneous","hidden":false}
            ]
    outputs:
      token: ${{ steps.generate_token.outputs.token }}
      release_created: ${{ steps.release_please.outputs.release_created }}
      upload_url: ${{ steps.release_please.outputs.upload_url }}
      html_url: ${{ steps.release_please.outputs.html_url }}
      tag_name: ${{ steps.release_please.outputs.tag_name }}
      major: ${{ steps.release_please.outputs.major }}
      minor: ${{ steps.release_please.outputs.minor }}
      patch: ${{ steps.release_please.outputs.patch }}
      sha: ${{ steps.release_please.outputs.sha }}
      pr: ${{ steps.release_please.outputs.pr }}

  publish:
    needs: [release]
    if: needs.release.outputs.release_created
    uses: ./.github/workflows/publish.yml
    with:
      token: ${{ needs.release.outputs.token }}
      upload_url: ${{ needs.release.outputs.upload_url }}
      html_url: ${{ needs.release.outputs.html_url }}
      tag_name: ${{ needs.release.outputs.tag_name }}
      major: ${{ needs.release.outputs.major }}
      minor: ${{ needs.release.outputs.minor }}
      patch: ${{ needs.release.outputs.patch }}
      sha: ${{ needs.release.outputs.sha }}
      pr: ${{ needs.release.outputs.pr }}
