on:
  push:
    branches:
      - master

env:
  CI: true
  GITHUB_CONTEXT: ${{ toJson(github) }}

jobs:
  checks:
    uses: ./.github/workflows/checks.yml

  release:
    needs: [checks]
    # see: https://github.com/actions/runner/issues/491
    if: |
      always() &&
      (needs.checks.result == 'success' || needs.checks.result == 'skipped')
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: false
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v3.1
        with:
          release-type: simple
          changelog-types: |
            [
              {"type":"feat","section":"Features","hidden":false},
              {"type":"fix","section":"Bug Fixes","hidden":false},
              {"type":"build","section":"Automation","hidden":false},
              {"type":"ci","section":"Automation","hidden":false},
              {"type":"docs","section":"Miscellaneous","hidden":false},
              {"type":"perf","section":"Miscellaneous","hidden":false},
              {"type":"refactor","section":"Miscellaneous","hidden":false},
              {"type":"style","section":"Miscellaneous","hidden":false},
              {"type":"test","section":"Miscellaneous","hidden":false},
              {"type":"chore","section":"Miscellaneous","hidden":false}
            ]
